openapi: 3.0.0
info:
  license:
    name: MIT
  title: Swagger Petstore
  version: 1.0.0
servers:
- url: http://petstore.swagger.io/v1
paths:
  /pets:
    post:
      operationId: createPets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePetData'
      responses:
        "201":
          description: Null response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: Create a pet
      tags:
      - pets
      x-content-type: application/json
      x-accepts: application/json
components:
  schemas:
    CreatePetData:
      example:
        name: jang
      properties:
        name:
          example: jang
          type: string
    Error:
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
      required:
      - code
      - message

