/*
 * Swagger Petstore
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.dhslrl321.openapi;

import com.github.dhslrl321.openapi.invoker.ApiException;
import com.github.dhslrl321.openapi.model.CreatePetData;
import com.github.dhslrl321.openapi.model.Error;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PetsApi
 */
@Disabled
public class PetsApiTest {

    private final PetsApi api = new PetsApi();

    /**
     * Create a pet
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createPetsTest() throws ApiException {
        CreatePetData createPetData = null;
        api.createPets(createPetData);
        // TODO: test validations
    }

}
